version: "3"
services:
  django-library:
    image: willdockerhub/django-library
    restart: always
    volumes:
      - "/data/django-library/conf/settings.py:/code/library/settings.py"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=library
      - MYSQL_USER=library
      - MYSQL_PASSWORD=library123

volumes:
  mysql:
